#!/usr/bin/env python3
import re
import os
from datetime import datetime, timedelta, timezone

def main():
    # 1. Read the massive Atlas generated file
    input_filename = '20260518060342_gorm.sql'
    if not os.path.exists(input_filename):
        print(f"❌ Error: Could not find '{input_filename}' in the current directory.")
        print("Please make sure your giant migration file is named 'migration.sql' or update the input_filename variable.")
        return

    with open(input_filename, 'r', encoding='utf-8') as f:
        content = f.read()

    # 2. Split into Up and Down sections
    if '-- +goose Down' not in content:
        print("❌ Error: The file does not contain a '-- +goose Down' marker.")
        print("Make sure it was generated by Atlas using the format modifier (e.g., ?format=goose passed to the --dir URL).")
        return

    up_text, down_text = content.split('-- +goose Down')

    # 3. Extract all UP statements and their table names
    # Matches the Atlas comment pattern and the following CREATE TABLE block until the trailing semicolon
    ups = re.findall(r'(-- create "([^"]+)" table\s+CREATE TABLE.*?;)', up_text, re.DOTALL | re.IGNORECASE)

    # 4. Extract all DOWN statements and their table names
    # Matches the Atlas reverse comment pattern and the following DROP TABLE block until the trailing semicolon
    downs = re.findall(r'(-- reverse: create "([^"]+)" table\s+DROP TABLE.*?;)', down_text, re.DOTALL | re.IGNORECASE)
    down_dict = {name: stmt for stmt, name in downs}

    output_dir = 'split_migrations'
    os.makedirs(output_dir, exist_ok=True)

    # 5. Establish the baseline timestamp in STRICT UTC
    # We increment by 1 second for each file to preserve Atlas's topological dependency sorting
    start_time = datetime.now(timezone.utc)

    print(f"Found {len(ups)} tables. Splitting into strict UTC timestamped migrations...")

    # 6. Generate the individual timestamped files
    for i, (up_stmt, table_name) in enumerate(ups):
        # Add 'i' seconds to the start time so each file is uniquely 1 second in the future.
        # This guarantees Goose sorts and executes them in the exact topological order Atlas intended.
        current_timestamp = start_time + timedelta(seconds=i)
        timestamp_str = current_timestamp.strftime("%Y%m%d%H%M%S")

        filename = os.path.join(output_dir, f"{timestamp_str}_create_{table_name}.sql")

        with open(filename, 'w', encoding='utf-8') as f:
            f.write("-- +goose Up\n")
            f.write(up_stmt.strip() + "\n\n")
            f.write("-- +goose Down\n")

            # Grab the matching DROP statement from the dictionary.
            # If for some reason Atlas didn't generate it, fallback to a standard generic DROP.
            drop_stmt = down_dict.get(table_name, f"DROP TABLE `{table_name}`;")
            f.write(drop_stmt.strip() + "\n")

    print(f"\n🎉 Success! Generated {len(ups)} strict UTC timestamped files in the '{output_dir}/' directory.")
    print("\nNext steps to lock this into your pipeline:")
    print(f" 1. Move the files from '{output_dir}/' directly into your Go project's migrations folder.")
    print(f" 2. Delete the temporary 'migration.sql' file.")
    print(f" 3. Run the hash command to fix the sum lockfile:")
    print(f"    atlas migrate hash --dir \"file://path/to/your/migrations?format=goose\"")

if __name__ == '__main__':
    main()
